In [1]:
import numpy as np
import pandas as pd

#### Concatenation

##### Concatenation is simply "pasting" two DataFrames together by columns or rows. Both DataFrames have to be in the same format

In [2]:
data_one = {'A': ['A0', 'A1', 'A2', 'A3'], 'B': ['B0', 'B1', 'B2', 'B3']}

In [3]:
data_two = {'C': ['C0', 'C1', 'C2', 'C3'], 'D': ['D0', 'D1', 'D2', 'D3']}

In [4]:
one = pd.DataFrame(data_one)

In [5]:
two = pd.DataFrame(data_two)

In [6]:
one

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [7]:
two

    C   D
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [8]:
# to specify the concatenation along the columns we need to add axis=1
pd.concat([one, two], axis=1)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [9]:
# Concatenating along the rows
pd.concat([one, two], axis=0)

     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3   A3   B3  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1
2  NaN  NaN   C2   D2
3  NaN  NaN   C3   D3

##### Pandas automatially fills the table with null values because you cannot have two items in the same position, namely A0 and C0

In [10]:
# Changing the columns of the second dataset to have the values on the same column
two.columns = one.columns

In [11]:
two

    A   B
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [12]:
# Now, concatenate by the rows
pd.concat([one, two], axis=0)

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [13]:
# To change the index to follow the right sequence
mydf = pd.concat([one, two], axis=0)

In [14]:
mydf.index = range(len(mydf))

In [15]:
mydf

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
4  C0  D0
5  C1  D1
6  C2  D2
7  C3  D3

#### Merge - Inner Merge

##### When DataFrames are not in the exact same order or format
Thhe .merge() method takes in a key argument labeled 'how'
There are 3 main ways of merging tables together using the 'how' parameter:
- Inner
Outer
Left or Right