In [1]:
import pandas as pd

#### CSV Files

In [2]:
# Find out what directory you're currently working in
%pwd

'C:\\Users\\inioluwa.daniel\\Documents\\DS_ML_COURSE\\NOTEBOOKS_DS_ML_COURSE\\03-Pandas'

In [3]:
# Check out the list of documents in that directory
%ls

 Volume in drive C has no label.
 Volume Serial Number is 587D-E488

 Directory of C:\Users\inioluwa.daniel\Documents\DS_ML_COURSE\NOTEBOOKS_DS_ML_COURSE\03-Pandas

03/06/2026  15:42    <DIR>          .
18/03/2026  09:56    <DIR>          ..
03/06/2026  15:36    <DIR>          .ipynb_checkpoints
17/02/2026  13:52    <DIR>          __pycache__
17/02/2026  13:52           565,390 00-Series.ipynb
17/03/2026  15:45           209,646 01-DataFrames.ipynb
17/02/2026  13:52           194,591 02-Conditional-Filtering.ipynb
27/04/2026  09:57           197,230 03-Useful-Methods.ipynb
14/05/2026  13:32            64,240 04-Missing-Data.ipynb
17/02/2026  13:52           219,627 05-Groupby-Operations-and-MultiIndex.ipynb
03/06/2026  12:02            63,031 06-Combining-DataFrames.ipynb
03/06/2026  13:39            33,193 07-Text-Methods.ipynb
03/06/2026  13:42            94,237 08-Time-Methods.ipynb
03/06/2026  15:37            65,299 09-Inputs-and-Outputs.ipynb
17/02/2026  13:52           101,081 10-Pivot-Tables.ipynb
17/02/2026  13:52            47,135 11-Pandas-Project-Exercise .ipynb
17/02/2026  13:52            52,576 12-Pandas-Project-Exercise-Solution.ipynb
03/06/2026  13:10            53,417 combining.ipynb
02/04/2026  09:06            53,897 conditional_filtering(pandas).ipynb
17/02/2026  13:52                51 example.csv
17/02/2026  13:52             5,022 example.xlsx
01/06/2026  16:06           180,177 GroupBy.ipynb
17/02/2026  13:52        25,112,317 hotel_booking_data.csv
03/06/2026  15:42             1,905 inputs_and_outputs.ipynb
15/05/2026  16:28            41,908 missing_data.ipynb
17/02/2026  13:52               177 movie_scores.csv
17/02/2026  13:52            17,727 mpg.csv
17/02/2026  13:52             5,022 my_excel_file.xlsx
17/02/2026  13:52                51 new_file.csv
17/02/2026  13:52             5,021 new_workbook.xlsx
17/02/2026  13:52                51 newfile.csv
25/03/2026  09:55           190,318 pandas.ipynb
17/02/2026  13:52            52,132 reshaping_pivot.png
17/02/2026  13:52             5,459 RetailSales_BeerWineLiquor.csv
17/02/2026  13:52             1,320 Sales_Funnel_CRM.csv
17/02/2026  13:52             1,330 sample_table.html
17/02/2026  13:52               555 simple.html
03/06/2026  13:40            10,515 text_methods.ipynb
03/06/2026  15:32            20,530 time_methods.ipynb
17/02/2026  13:52            18,752 tips.csv
14/05/2026  13:07            84,226 useful_methods_in_pandas.ipynb
              37 File(s)     27,769,156 bytes
               4 Dir(s)  328,360,878,080 bytes free

In [4]:
df = pd.read_csv('example.csv')

In [5]:
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [6]:
# Make some changes to the csv
df = pd.read_csv('example.csv', index_col=0)

df

In [8]:
# Save the dataframe. We can either input a name or a file path to save the file
df.to_csv('newfile.csv', index=True)

In [9]:
new = pd.read_csv('newfile.csv')

In [10]:
new

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

#### HTML Tables

In [11]:
# We'll get the table data from a website
url = "https://en.wikipedia.org/wiki/World_population"

In [19]:
tables = pd.read_html('sample_table.html')

In [20]:
len(tables)

1

In [21]:
tables[0]

          Country   200  2015  2030 Est.
0        China[B]  1270  1376       1416
1           India  1053  1311       1528
2   United States   283   322        356
3       Indonesia   212   258        295
4        Pakistan   136   208        245
5          Brazil   176   206        228
6         Nigeria   123   182        263
7      Bangladesh   131   161        186
8          Russia   146   146        149
9          Mexico   103   127        148
10    World total  6127  7349       8501

#### Excel

In [23]:
df = pd.read_excel('my_excel_file.xlsx', sheet_name='First_Sheet')

In [24]:
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [25]:
# Running a loop through all the sheet names in the case where we do not know the names of the sheets (with larger workbooks)
work_book = pd.ExcelFile('my_excel_file.xlsx')

In [26]:
work_book.sheet_names

['First_Sheet']

In [27]:
excel_sheet_dict = pd.read_excel('my_excel_file.xlsx', sheet_name=None)